/**
 * 《八天无极微循环 · ACSM 2026》训练计划数据库（V2.8 全量拆卡版）
 *
 * 铁律：
 *  - 凡是可能使用不同重量的动作（复合动作 / “或者”关系）一律拆分为拥有独立 id 的独立卡片
 *  - 每个场馆（newGym 乐刻新馆 / oldGym 传统旧馆 / home 家庭重装）均写入 defaultWeight、sets、defaultRepsList，彻底消灭初始 0kg
 *
 * 字段：
 *  - venues        该动作在哪些场馆出现
 *  - variants[v]   name / machineCode / isPlateLoaded / defaultWeight / sets / defaultRepsList / defaultSeatNote
 *  - prescription  sets / repRange / targetRIR / restSeconds / day5SourceId
 *  - type          普通卡省略；超级组为 'superset' 并内嵌 subExercises: [A, B]
 */

const P = (sets, min, max, rir, rest, day5SourceId = null) => ({
  sets,
  repRange: [min, max],
  targetRIR: rir,
  restSeconds: rest,
  day5SourceId,
})

const T = (con, conTime, ecc, eccTime, bottom, overload) => ({
  concentric: { time: conTime, cue: con },
  topPause: { time: '0–1秒', cue: '顶点挤压/微屈不锁死，保持张力' },
  eccentric: { time: eccTime, cue: ecc },
  bottomPause: { time: '1秒', cue: bottom },
  overloadCue: overload,
})

const M = (type, points) => ({
  version: 1,
  placeholderSvgType: type,
  machinePhotoUrl: null,
  actionDiagramUrl: null,
  keyPointsOverlay: points,
})

/** 紧凑场馆变体工厂：name / machineCode / defaultWeight / 组数 / 每组默认次数（自带递减阶梯） */
const V = (name, machineCode, defaultWeight, sets, reps, opts = {}) => ({
  name,
  machineCode,
  defaultWeight,
  sets,
  defaultRepsList: reps,
  repRange: opts.repRange || [Math.min(...reps), Math.max(...reps)],
  isPlateLoaded: Boolean(opts.plate),
  defaultSeatNote: opts.seat || '标准机位',
})

const ALL = ['newGym', 'oldGym', 'home']
const COMMERCIAL = ['newGym', 'oldGym']

/* 复用型四段式节奏模板 */
const TEMPO_POWER = T(
  '前 2/3 程全力加速，末端 15° 主动减速刹车',
  '<1秒',
  '稳稳下放，底部停稳再发力',
  '2秒',
  '底部停稳卸掉惯性，严禁锁死弹震',
  '追求神经放电速度，总次数不贪多'
)
const TEMPO_COMPOUND = T(
  '发力向心 1 秒，顶点微屈不锁死',
  '1秒',
  '控制下放至拉伸位',
  '2秒',
  '🛑 底部稳停 1 秒卸掉反弹力',
  '向心速度变慢即停，不硬撑力竭'
)
const TEMPO_ISO = T(
  '顶峰挤压 1 秒',
  '1秒',
  '缓慢还原，全程保持张力',
  '2秒',
  '顶峰/底部停顿 1 秒',
  '出现速度变慢即停，保持代谢压力'
)
const TEMPO_CORE = T('收紧腹背保持高张力', '静态', '保持', '静态', '全程高张力不塌腰', '按秒计时，追求质量而非时长')

export const PLAN_LIBRARY = [
  // ============================== LEO ==============================
  // ---------- Day 1 下肢重装日 ----------
  {
    id: 'leo_d1_e1a',
    user: 'leo',
    day: 1,
    order: 'A1 哈克蹬伸',
    muscleGroup: 'quads',
    category: 'power',
    venues: ALL,
    variants: {
      newGym: V('哈克机快速蹬伸', '爆发力激活 · 50%正式重', 30, 2, [5, 5]),
      oldGym: V('史密斯快速半蹲', '旧馆 · 爆发力激活', 30, 2, [5, 5]),
      home: V('哑铃双向摆荡', '家庭 · 爆发力替代', 16, 2, [5, 5]),
    },
    prescription: P(2, 5, 5, 3, 120),
    tempoGuide: TEMPO_POWER,
    media: M('power_leg', ['爆发加速', '末端15°刹车', '不锁膝']),
  },
  {
    id: 'leo_d1_e1b',
    user: 'leo',
    day: 1,
    order: 'A2 腿举蹬伸',
    muscleGroup: 'quads',
    category: 'power',
    venues: ALL,
    variants: {
      newGym: V('坐姿腿举机快速蹬伸', '爆发力激活 · 50%正式重', 60, 2, [5, 5]),
      oldGym: V('45°倒蹬快速蹬伸', '旧馆 · 爆发力激活', 70, 2, [5, 5]),
      home: V('哑铃快速分腿蹲', '家庭 · 爆发力替代', 10, 2, [5, 5]),
    },
    prescription: P(2, 5, 5, 3, 120),
    tempoGuide: TEMPO_POWER,
    media: M('power_leg', ['爆发加速', '末端15°刹车', '不锁膝']),
  },
  {
    id: 'leo_d1_e2a',
    user: 'leo',
    day: 1,
    order: '主项1A 哈克深蹲',
    muscleGroup: 'quads',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('商业哈克深蹲机', '商业健身房 · 哈克机', 50, 3, [10, 10, 8], { seat: '肩垫居中 | 脚距与肩同宽' }),
      oldGym: V('史密斯深蹲', '旧馆 · 史密斯', 50, 3, [10, 10, 8], { seat: '杠位居中' }),
      home: V('哑铃保加利亚分腿蹲', '家庭 · 哑铃', 15, 3, [10, 10, 8], { seat: '后脚搭凳面，躯干前倾 15°' }),
    },
    prescription: P(3, 8, 12, 2, 150),
    tempoGuide: TEMPO_COMPOUND,
    media: M('squat', ['脚跟发力', '顶点不锁死', '底部停1秒']),
  },
  {
    id: 'leo_d1_e2b',
    user: 'leo',
    day: 1,
    order: '主项1B 腿举/倒蹬',
    muscleGroup: 'quads',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('坐姿腿举机', '商业健身房 · 腿举机', 90, 3, [12, 10, 10], { seat: '背板贴合' }),
      oldGym: V('45°挂片倒蹬机', '旧馆 · 挂片倒蹬', 100, 3, [12, 10, 10], { seat: '踏板居中', plate: true }),
      home: V('宽距酒杯深蹲', '家庭 · 哑铃', 22.5, 3, [12, 10, 10], { seat: '哑铃抱于胸前' }),
    },
    prescription: P(3, 10, 12, 2, 150),
    tempoGuide: TEMPO_COMPOUND,
    media: M('leg_press', ['踏板居中', '顶点不锁死', '底部停1秒']),
  },
  {
    id: 'leo_d1_e3a',
    user: 'leo',
    day: 1,
    order: '主项2A 奥杆RDL',
    muscleGroup: 'glutes_hams',
    category: 'compound',
    venues: COMMERCIAL,
    variants: {
      newGym: V('【图1】奥杆杠铃罗马尼亚硬拉 RDL', '图1 · 奥杆木质平台', 50, 3, [10, 10, 8], { seat: '挂助握带', plate: true }),
      oldGym: V('杠铃罗马尼亚硬拉 RDL', '旧馆 · 自由重量', 50, 3, [10, 10, 8], { seat: '挂助握带' }),
    },
    prescription: P(3, 8, 12, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('hinge', ['臀向后推', '杠贴腿', '底端停1秒']),
  },
  {
    id: 'leo_d1_e3b',
    user: 'leo',
    day: 1,
    order: '主项2B 哑铃RDL',
    muscleGroup: 'glutes_hams',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('双手哑铃罗马尼亚硬拉 RDL', '新馆 · 哑铃（单只计）', 20, 3, [12, 10, 10], { seat: '挂助握带' }),
      oldGym: V('双手哑铃罗马尼亚硬拉 RDL', '旧馆 · 哑铃（单只计）', 20, 3, [12, 10, 10], { seat: '挂助握带' }),
      home: V('双手哑铃罗马尼亚硬拉 RDL', '家庭 · 哑铃（单只计）', 22.5, 3, [12, 10, 10], { seat: '膝微屈固定' }),
    },
    prescription: P(3, 10, 12, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('hinge', ['臀向后推', '杠贴腿', '底端停1秒']),
  },
  {
    id: 'leo_d1_e4a',
    user: 'leo',
    day: 1,
    order: '主项3A 坐姿腿弯举',
    muscleGroup: 'glutes_hams',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('坐姿腿弯举机', '新馆 · 插销器械', 40, 3, [15, 12, 12], { seat: '滚轴压踝上，膝对齐转轴' }),
      oldGym: V('坐姿腿弯举', '旧馆 · 插销器械', 40, 3, [15, 12, 12], { seat: '膝对齐转轴' }),
      home: V('仰卧滑盘双腿弯举', '家庭 · 滑盘', 0, 3, [15, 12, 12], { seat: '仰卧脚跟置于滑盘' }),
    },
    prescription: P(3, 10, 15, 1, 90),
    tempoGuide: TEMPO_ISO,
    media: M('leg_curl', ['顶峰停1秒', '离心2秒', '末组单腿慢放']),
  },
  {
    id: 'leo_d1_e4b',
    user: 'leo',
    day: 1,
    order: '主项3B 俯卧腿弯举',
    muscleGroup: 'glutes_hams',
    category: 'isolation',
    venues: COMMERCIAL,
    variants: {
      newGym: V('俯卧腿弯举机', '新馆 · 插销器械', 30, 2, [12, 10], { seat: '俯卧，滚轴压踝上' }),
      oldGym: V('俯卧腿弯举机', '旧馆 · 插销器械', 30, 2, [12, 10], { seat: '俯卧，滚轴压踝上' }),
    },
    prescription: P(2, 10, 15, 1, 90),
    tempoGuide: TEMPO_ISO,
    media: M('leg_curl', ['顶峰停1秒', '离心2秒']),
  },
  {
    id: 'leo_d1_e5',
    user: 'leo',
    day: 1,
    order: '主项4 腿屈伸',
    muscleGroup: 'quads',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('坐姿腿屈伸机', '新馆 · 插销器械', 45, 3, [15, 12, 12], { seat: '膝对齐转轴' }),
      oldGym: V('坐姿腿屈伸机', '旧馆 · 插销器械', 45, 3, [15, 12, 12], { seat: '膝对齐转轴' }),
      home: V('靠墙静蹲夹球 / 慢速深蹲', '家庭 · 徒手', 15, 3, [15, 12, 12], { seat: '大腿尽量与地面平行' }),
    },
    prescription: P(3, 12, 15, 1, 90),
    tempoGuide: TEMPO_ISO,
    media: M('leg_ext', ['顶峰停1秒', '离心2秒']),
  },
  {
    id: 'leo_d1_e6',
    user: 'leo',
    day: 1,
    order: '主项5 提踵',
    muscleGroup: 'calves',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('腿举机 / 立姿器械提踵', '新馆 · 插销器械', 60, 3, [20, 18, 15], { seat: '前脚掌踩踏板边缘' }),
      oldGym: V('史密斯提踵', '旧馆 · 史密斯', 50, 3, [20, 18, 15], { seat: '前脚掌踩踏板' }),
      home: V('单腿台阶哑铃提踵', '家庭 · 哑铃', 12.5, 3, [20, 18, 15], { seat: '台阶边缘' }),
    },
    prescription: P(3, 15, 20, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('calf', ['顶峰停1秒', '底部拉伸']),
  },
  {
    id: 'leo_d1_e7',
    user: 'leo',
    day: 1,
    order: '收尾 核心',
    muscleGroup: 'arms',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('RKC 高张力平板支撑', '新馆 · 徒手（按秒）', 0, 3, [45, 45, 45], { seat: '收紧腹背不塌腰' }),
      oldGym: V('悬垂举腿', '旧馆 · 单杠（按秒/次）', 0, 3, [45, 45, 45], { seat: '核心收紧' }),
      home: V('RKC 高张力平板支撑', '家庭 · 徒手（按秒）', 0, 3, [45, 45, 45], { seat: '收紧腹背不塌腰' }),
    },
    prescription: P(3, 30, 45, 1, 60),
    tempoGuide: TEMPO_CORE,
    media: M('core', ['收紧腹背', '不塌腰', '按秒计时']),
  },

  // ---------- Day 3 胸肩三头 ----------
  {
    id: 'leo_d3_e1',
    user: 'leo',
    day: 3,
    order: '热身 肩袖',
    muscleGroup: 'shoulders',
    category: 'warmup',
    venues: ALL,
    variants: {
      newGym: V('绳索肩袖外旋 YTWL 激活', '新馆 · 龙门架', 2.5, 2, [15, 15], { seat: '肘贴身' }),
      oldGym: V('弹力带肩袖外旋 YTWL', '旧馆 · 弹力带', 2.5, 2, [15, 15], { seat: '肘贴身' }),
      home: V('弹力带肩袖外旋 YTWL', '家庭 · 弹力带', 0, 2, [15, 15], { seat: '肘贴身' }),
    },
    prescription: P(2, 15, 15, 1, 45),
    tempoGuide: TEMPO_ISO,
    media: M('rotator', ['肘贴身', '慢速控制']),
  },
  {
    id: 'leo_d3_e2',
    user: 'leo',
    day: 3,
    order: '主项1 水平卧推',
    muscleGroup: 'chest',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图2/3】挂片水平卧推机', '图2/3 · 挂片', 30, 3, [10, 8, 8], { plate: true, seat: '座椅与握把同高' }),
      oldGym: V('平板杠铃卧推', '旧馆 · 自由重量', 50, 3, [10, 8, 8], { seat: '躺平，杠位于乳头线' }),
      home: V('平板哑铃卧推（单手）', '家庭 · 哑铃（单只计）', 20, 3, [10, 8, 8], { seat: '肘部约 45°' }),
    },
    prescription: P(3, 8, 12, 2, 150),
    tempoGuide: TEMPO_COMPOUND,
    media: M('chest_press', ['沉肩', '底部拉伸', '顶点不锁死']),
  },
  {
    id: 'leo_d3_e3',
    user: 'leo',
    day: 3,
    order: '主项2 上斜推胸',
    muscleGroup: 'chest',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图6】挂片坐姿上斜推胸', '图6 · 挂片', 25, 3, [12, 10, 10], { plate: true, seat: '座椅调至上斜位' }),
      oldGym: V('上斜哑铃卧推（单手）', '旧馆 · 哑铃（单只计）', 17.5, 3, [12, 10, 10], { seat: '靠背约 30°' }),
      home: V('30°上斜哑铃卧推（单手）', '家庭 · 哑铃（单只计）', 17.5, 3, [12, 10, 10], { seat: '靠背约 30°' }),
    },
    prescription: P(3, 10, 12, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('incline_press', ['沉肩', '底部拉伸', '顶点不锁死']),
  },
  {
    id: 'leo_d3_e4',
    user: 'leo',
    day: 3,
    order: '主项3 夹胸',
    muscleGroup: 'chest',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('【图4/5】站立飞鸟机夹胸', '图4/5 · 飞鸟机', 20, 3, [15, 12, 12], { seat: '肘微屈固定' }),
      oldGym: V('坐姿蝴蝶机夹胸', '旧馆 · 蝴蝶机', 35, 3, [15, 12, 12], { seat: '背板贴紧' }),
      home: V('仰卧哑铃飞鸟', '家庭 · 哑铃（单只计）', 12.5, 3, [15, 12, 12], { seat: '肘微屈' }),
    },
    prescription: P(3, 12, 15, 1, 90),
    tempoGuide: TEMPO_ISO,
    media: M('fly', ['顶峰挤压1秒', '离心2秒']),
  },
  {
    id: 'leo_d3_e5a',
    user: 'leo',
    day: 3,
    order: '主项4A 器械推肩',
    muscleGroup: 'shoulders',
    category: 'compound',
    venues: COMMERCIAL,
    variants: {
      newGym: V('坐姿器械推肩机', '新馆 · 插销器械', 30, 3, [10, 10, 8], { seat: '握把与肩同高' }),
      oldGym: V('坐姿器械推肩机', '旧馆 · 插销器械', 30, 3, [10, 10, 8], { seat: '握把与肩同高' }),
    },
    prescription: P(3, 8, 12, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('shoulder_press', ['沉肩', '顶点不锁死']),
  },
  {
    id: 'leo_d3_e5b',
    user: 'leo',
    day: 3,
    order: '主项4B 哑铃推肩',
    muscleGroup: 'shoulders',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('坐姿哑铃推肩（单手）', '新馆 · 哑铃（单只计）', 15, 3, [12, 10, 10], { seat: '靠背约 75°' }),
      oldGym: V('坐姿哑铃推肩（单手）', '旧馆 · 哑铃（单只计）', 15, 3, [12, 10, 10], { seat: '靠背约 75°' }),
      home: V('坐姿哑铃推肩（单手）', '家庭 · 哑铃（单只计）', 15, 3, [12, 10, 10], { seat: '靠背约 75°' }),
    },
    prescription: P(3, 10, 12, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('shoulder_press', ['沉肩', '顶点不锁死']),
  },
  {
    id: 'leo_d3_e6a',
    user: 'leo',
    day: 3,
    order: '主项5A 器械侧平举',
    muscleGroup: 'shoulders',
    category: 'isolation',
    venues: COMMERCIAL,
    variants: {
      newGym: V('【图4/5】站立侧平举机', '图4/5 · LATERAL', 15, 4, [16, 15, 15, 12], { seat: '肘垫贴合' }),
      oldGym: V('龙门架单臂绳索侧平举', '旧馆 · 龙门架', 7.5, 4, [16, 15, 15, 12], { seat: '低位滑轮' }),
    },
    prescription: P(4, 12, 20, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('lateral_raise', ['抬至肩高', '顶峰停0.5秒']),
  },
  {
    id: 'leo_d3_e6b',
    user: 'leo',
    day: 3,
    order: '主项5B 哑铃侧平举',
    muscleGroup: 'shoulders',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('站姿哑铃侧平举（单手）', '新馆 · 哑铃（单只计）', 8, 4, [16, 15, 15, 12], { seat: '肘微屈' }),
      oldGym: V('站姿哑铃侧平举（单手）', '旧馆 · 哑铃（单只计）', 8, 4, [16, 15, 15, 12], { seat: '肘微屈' }),
      home: V('坐姿哑铃侧平举（单手）', '家庭 · 哑铃（单只计）', 8, 4, [16, 15, 15, 12], { seat: '肘微屈' }),
    },
    prescription: P(4, 12, 20, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('lateral_raise', ['抬至肩高', '顶峰停0.5秒']),
  },
  {
    id: 'leo_d3_e7a',
    user: 'leo',
    day: 3,
    order: '主项6A 绳索三头下压',
    muscleGroup: 'arms',
    category: 'isolation',
    venues: COMMERCIAL,
    variants: {
      newGym: V('龙门架绳索 / V把三头下压', '新馆 · 龙门架', 25, 3, [15, 12, 12], { seat: '插销档位' }),
      oldGym: V('龙门架三头下压', '旧馆 · 龙门架', 25, 3, [15, 12, 12], { seat: '插销档位' }),
    },
    prescription: P(3, 12, 15, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('triceps', ['伸肘到底停1秒', '底部拉长位停顿']),
  },
  {
    id: 'leo_d3_e7b',
    user: 'leo',
    day: 3,
    order: '主项6B 哑铃臂屈伸',
    muscleGroup: 'arms',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('仰卧哑铃颈后臂屈伸', '新馆 · 哑铃（单只计）', 10, 3, [15, 12, 12], { seat: '肘尖朝上' }),
      oldGym: V('仰卧哑铃颈后臂屈伸', '旧馆 · 哑铃（单只计）', 10, 3, [15, 12, 12], { seat: '肘尖朝上' }),
      home: V('仰卧哑铃颈后臂屈伸', '家庭 · 哑铃（单只计）', 10, 3, [15, 12, 12], { seat: '肘尖朝上' }),
    },
    prescription: P(3, 12, 15, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('triceps', ['伸肘到底停1秒', '底部拉长位停顿']),
  },

  // ---------- Day 4 背部二头 ----------
  {
    id: 'leo_d4_e1a',
    user: 'leo',
    day: 4,
    order: '主项1A 挂片划船',
    muscleGroup: 'back',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图10/12】挂片式长臂坐姿划船', '图10/12 · 挂片', 25, 3, [10, 10, 8], { plate: true, seat: '胸垫贴紧' }),
      oldGym: V('坐姿窄距绳索划船', '旧馆 · 龙门架', 45, 3, [10, 10, 8], { seat: '胸垫贴紧' }),
      home: V('单臂哑铃划船', '家庭 · 哑铃（单只计）', 22.5, 3, [10, 10, 8], { seat: '手撑凳面' }),
    },
    prescription: P(3, 8, 12, 2, 150),
    tempoGuide: TEMPO_COMPOUND,
    media: M('row', ['沉肩用手肘拉', '顶峰夹紧', '底部打开肩胛']),
  },
  {
    id: 'leo_d4_e1b',
    user: 'leo',
    day: 4,
    order: '主项1B 胸垫划船',
    muscleGroup: 'back',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图9/11】插销式胸垫划船机', '图9/11 · 插销秒调', 40, 3, [12, 10, 10], { seat: '胸垫贴紧' }),
      oldGym: V('俯身杠铃划船', '旧馆 · 自由重量', 45, 3, [12, 10, 10], { seat: '髋屈约 45°' }),
      home: V('胸部支撑哑铃划船', '家庭 · 哑铃（单只计）', 17.5, 3, [12, 10, 10], { seat: '趴凳支撑' }),
    },
    prescription: P(3, 10, 12, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('row', ['沉肩用手肘拉', '顶峰夹紧', '底部打开肩胛']),
  },
  {
    id: 'leo_d4_e2a',
    user: 'leo',
    day: 4,
    order: '主项2A 高位下拉',
    muscleGroup: 'back',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('宽握高位下拉机', '新馆 · 插销器械', 45, 4, [12, 10, 10, 8], { seat: '大腿固定' }),
      oldGym: V('宽握高位下拉', '旧馆 · 龙门架', 45, 4, [12, 10, 10, 8], { seat: '大腿固定' }),
      home: V('重型弹力带高位下拉', '家庭 · 弹力带', 20, 4, [12, 10, 10, 8], { seat: '弹力带固定高处' }),
    },
    prescription: P(4, 8, 12, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('pulldown', ['沉肩', '拉至锁骨', '慢放回']),
  },
  {
    id: 'leo_d4_e2b',
    user: 'leo',
    day: 4,
    order: '主项2B 助力引体',
    muscleGroup: 'back',
    category: 'compound',
    venues: COMMERCIAL,
    variants: {
      newGym: V('助力引体向上机', '新馆 · 助力抵扣', 20, 3, [8, 8, 6], { seat: '跪垫扣紧' }),
      oldGym: V('助力引体向上机', '旧馆 · 助力抵扣', 20, 3, [8, 8, 6], { seat: '跪垫扣紧' }),
    },
    prescription: P(3, 6, 10, 2, 150),
    tempoGuide: TEMPO_COMPOUND,
    media: M('pullup', ['沉肩', '拉至下巴过杠']),
  },
  {
    id: 'leo_d4_e3',
    user: 'leo',
    day: 4,
    order: '主项3 直臂下压',
    muscleGroup: 'back',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('龙门架绳索直臂下压', '新馆 · 龙门架', 20, 3, [15, 12, 12], { seat: '肘微屈固定' }),
      oldGym: V('龙门架绳索直臂下压', '旧馆 · 龙门架', 20, 3, [15, 12, 12], { seat: '肘微屈固定' }),
      home: V('弹力带直臂下压', '家庭 · 弹力带', 15, 3, [15, 12, 12], { seat: '肘微屈固定' }),
    },
    prescription: P(3, 12, 15, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('pulldown', ['肘微屈', '下拉到底挤压']),
  },
  {
    id: 'leo_d4_e4a',
    user: 'leo',
    day: 4,
    order: '主项4A 后束飞鸟',
    muscleGroup: 'shoulders',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('【图4/5】站立后束飞鸟机', '图4/5 · REAR', 15, 3, [18, 15, 15], { seat: '胸垫贴紧' }),
      oldGym: V('蝴蝶机反向后束', '旧馆 · 蝴蝶机', 25, 3, [18, 15, 15], { seat: '反坐，胸贴靠背' }),
      home: V('俯身哑铃后束飞鸟', '家庭 · 哑铃（单只计）', 6, 3, [18, 15, 15], { seat: '俯身约 30°' }),
    },
    prescription: P(3, 15, 20, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('rear_delt', ['向后展肩停1秒', '缓慢还原']),
  },
  {
    id: 'leo_d4_e4b',
    user: 'leo',
    day: 4,
    order: '主项4B 绳索面拉',
    muscleGroup: 'shoulders',
    category: 'isolation',
    venues: COMMERCIAL,
    variants: {
      newGym: V('龙门架绳索面拉 Face Pull', '新馆 · 龙门架', 20, 3, [18, 15, 15], { seat: '滑轮调至面部高度' }),
      oldGym: V('龙门架绳索面拉 Face Pull', '旧馆 · 龙门架', 20, 3, [18, 15, 15], { seat: '滑轮调至面部高度' }),
    },
    prescription: P(3, 15, 20, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('rear_delt', ['向后展肩停1秒', '缓慢还原']),
  },
  {
    id: 'leo_d4_e5a',
    user: 'leo',
    day: 4,
    order: '主项5A 牧师凳弯举',
    muscleGroup: 'arms',
    category: 'isolation',
    venues: COMMERCIAL,
    variants: {
      newGym: V('【图8】坐姿牧师凳二头弯举机', '图8 · 牧师凳', 25, 3, [12, 12, 10], { seat: '腋下死贴斜托上沿' }),
      oldGym: V('EZ 曲杆牧师凳弯举', '旧馆 · EZ 杆', 22.5, 3, [12, 12, 10], { seat: '腋下死贴斜托上沿' }),
    },
    prescription: P(3, 10, 15, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('biceps', ['弯起顶峰停1秒', '底部留10°微屈']),
  },
  {
    id: 'leo_d4_e5b',
    user: 'leo',
    day: 4,
    order: '主项5B 哑铃弯举',
    muscleGroup: 'arms',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('上斜哑铃交替弯举（单手）', '新馆 · 哑铃（单只计）', 12.5, 3, [12, 12, 10], { seat: '靠背 45°' }),
      oldGym: V('站姿哑铃交替弯举（单手）', '旧馆 · 哑铃（单只计）', 12.5, 3, [12, 12, 10], { seat: '肘固定' }),
      home: V('站姿哑铃交替弯举（单手）', '家庭 · 哑铃（单只计）', 12.5, 3, [12, 12, 10], { seat: '肘固定' }),
    },
    prescription: P(3, 10, 15, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('biceps', ['弯起顶峰停1秒', '底部留10°微屈']),
  },

  // ---------- Day 5 第二遍扩次日（85%） ----------
  {
    id: 'leo_d5_e1a',
    user: 'leo',
    day: 5,
    order: '1A 哈克85%',
    muscleGroup: 'quads',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('哈克深蹲机（85%扩次）', '主日 85% 重量', 42.5, 3, [15, 12, 12], { seat: '同 Day1 主项1A' }),
      oldGym: V('史密斯深蹲（85%扩次）', '旧馆 85% 重量', 42.5, 3, [15, 12, 12], { seat: '同主日' }),
      home: V('哑铃保加利亚分腿蹲（85%）', '家庭 85%', 12.5, 3, [15, 12, 12], { seat: '同主日' }),
    },
    prescription: P(3, 12, 16, 2, 120, ['leo_d1_e2a', 'leo_d1_e2b']),
    tempoGuide: TEMPO_COMPOUND,
    media: M('squat', ['85%重量', '冲12-16次']),
  },
  {
    id: 'leo_d5_e1b',
    user: 'leo',
    day: 5,
    order: '1B 腿举/倒蹬85%',
    muscleGroup: 'quads',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('坐姿腿举机（85%扩次）', '主日 85% 重量', 77.5, 3, [15, 15, 12], { seat: '同 Day1 主项1B' }),
      oldGym: V('45°挂片倒蹬机（85%扩次）', '旧馆 85% 重量', 85, 3, [15, 15, 12], { plate: true, seat: '同主日' }),
      home: V('宽距酒杯深蹲（85%扩次）', '家庭 85%', 20, 3, [15, 15, 12], { seat: '同主日' }),
    },
    prescription: P(3, 12, 16, 2, 120, ['leo_d1_e2b', 'leo_d1_e2a']),
    tempoGuide: TEMPO_COMPOUND,
    media: M('leg_press', ['85%重量', '冲12-16次']),
  },
  {
    id: 'leo_d5_e2a',
    user: 'leo',
    day: 5,
    order: '2A 坐姿腿弯举85%',
    muscleGroup: 'glutes_hams',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('坐姿腿弯举机（85%扩次）', '主日 85%', 35, 3, [15, 15, 12], { seat: '滚轴压踝上' }),
      oldGym: V('坐姿腿弯举（85%扩次）', '旧馆 85%', 35, 3, [15, 15, 12], { seat: '滚轴压踝上' }),
      home: V('仰卧滑盘腿弯举（85%扩次）', '家庭 85%', 0, 3, [15, 15, 12], { seat: '仰卧滑盘' }),
    },
    prescription: P(3, 12, 18, 2, 90, ['leo_d1_e4a', 'leo_d1_e4b']),
    tempoGuide: TEMPO_ISO,
    media: M('leg_curl', ['85%重量', '冲12-18次', '不做RDL']),
  },
  {
    id: 'leo_d5_e2b',
    user: 'leo',
    day: 5,
    order: '2B RDL/臀推85%',
    muscleGroup: 'glutes_hams',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('奥杆 RDL 或臀推（85%扩次）', '主日 85%', 42.5, 3, [12, 12, 10], { plate: true, seat: '挂助握带' }),
      oldGym: V('杠铃 RDL（85%扩次）', '旧馆 85%', 42.5, 3, [12, 12, 10], { seat: '挂助握带' }),
      home: V('哑铃臀推（85%扩次）', '家庭 85%', 20, 3, [12, 12, 10], { seat: '肩胛靠凳沿' }),
    },
    prescription: P(3, 12, 16, 2, 120, ['leo_d1_e3a', 'leo_d1_e4a']),
    tempoGuide: TEMPO_COMPOUND,
    media: M('hinge', ['85%重量', '冲12-16次']),
  },
  {
    id: 'leo_d5_e3a',
    user: 'leo',
    day: 5,
    order: '3A 坐姿推胸85%',
    muscleGroup: 'chest',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图6】挂片坐姿推胸（85%）', '图6 · 85%挂片', 22.5, 3, [15, 12, 12], { plate: true, seat: '同 Day3' }),
      oldGym: V('上斜哑铃卧推（85%）', '旧馆 85%（单只计）', 15, 3, [15, 12, 12], { seat: '同主日' }),
      home: V('哑铃卧推（85%）', '家庭 85%（单只计）', 15, 3, [15, 12, 12], { seat: '同主日' }),
    },
    prescription: P(3, 12, 16, 2, 120, ['leo_d3_e3', 'leo_d3_e2']),
    tempoGuide: TEMPO_COMPOUND,
    media: M('chest_press', ['85%重量', '冲12-16次']),
  },
  {
    id: 'leo_d5_e3b',
    user: 'leo',
    day: 5,
    order: '3B 水平卧推85%',
    muscleGroup: 'chest',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图2/3】挂片水平卧推（85%）', '图2/3 · 85%挂片', 25, 3, [12, 12, 10], { plate: true, seat: '同 Day3' }),
      oldGym: V('平板杠铃卧推（85%）', '旧馆 85%', 42.5, 3, [12, 12, 10], { seat: '同主日' }),
      home: V('平板哑铃卧推（85%，单只计）', '家庭 85%', 17.5, 3, [12, 12, 10], { seat: '同主日' }),
    },
    prescription: P(3, 12, 16, 2, 120, ['leo_d3_e2', 'leo_d3_e3']),
    tempoGuide: TEMPO_COMPOUND,
    media: M('chest_press', ['85%重量', '冲12-16次']),
  },
  {
    id: 'leo_d5_e4',
    user: 'leo',
    day: 5,
    order: '4 胸垫划船85%',
    muscleGroup: 'back',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图9/11】插销式胸垫划船（85%）', '图9/11 · 85%', 35, 3, [15, 12, 12], { seat: '胸垫贴紧' }),
      oldGym: V('俯身杠铃划船（85%）', '旧馆 85%', 37.5, 3, [15, 12, 12], { seat: '同主日' }),
      home: V('单臂哑铃划船（85%，单只计）', '家庭 85%', 15, 3, [15, 12, 12], { seat: '同主日' }),
    },
    prescription: P(3, 12, 16, 2, 120, ['leo_d4_e1b', 'leo_d4_e1a']),
    tempoGuide: TEMPO_COMPOUND,
    media: M('row', ['85%重量', '冲12-16次']),
  },
  {
    id: 'leo_d5_e5',
    user: 'leo',
    day: 5,
    order: '5 侧平举原重',
    muscleGroup: 'shoulders',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('【图4/5】站立侧平举（100%原重）', '图4/5 · 原重巩固', 15, 2, [18, 15], { seat: '同 Day3' }),
      oldGym: V('龙门架绳索侧平举（100%原重）', '旧馆 · 原重巩固', 7.5, 2, [18, 15], { seat: '同主日' }),
      home: V('哑铃侧平举（100%原重，单只计）', '家庭 · 原重巩固', 8, 2, [18, 15], { seat: '同主日' }),
    },
    prescription: P(2, 15, 20, 1, 60, 'leo_d3_e6a'),
    tempoGuide: TEMPO_ISO,
    media: M('lateral_raise', ['100%原重量', '2组']),
  },
  {
    id: 'leo_d5_ss1',
    user: 'leo',
    day: 5,
    order: '6 手臂超级组',
    muscleGroup: 'arms',
    category: 'isolation',
    venues: ALL,
    type: 'superset',
    subExercises: [
      {
        id: 'leo_d5_ss1_a',
        user: 'leo',
        day: 5,
        order: '超级组A 弯举',
        muscleGroup: 'arms',
        category: 'isolation',
        venues: ALL,
        variants: {
          newGym: V('【图8】牧师凳弯举（100%原重）', '图8 · 牧师凳', 25, 2, [15, 12], { seat: '腋下死贴斜托' }),
          oldGym: V('哑铃交替弯举（100%原重）', '旧馆 · 哑铃（单只计）', 12.5, 2, [15, 12], { seat: '肘固定' }),
          home: V('哑铃弯举（100%原重）', '家庭 · 哑铃（单只计）', 12.5, 2, [15, 12], { seat: '肘固定' }),
        },
        prescription: P(2, 12, 15, 1, 60),
        tempoGuide: TEMPO_ISO,
        media: M('biceps', ['原重巩固', '2组']),
      },
      {
        id: 'leo_d5_ss1_b',
        user: 'leo',
        day: 5,
        order: '超级组B 三头下压',
        muscleGroup: 'arms',
        category: 'isolation',
        venues: ALL,
        variants: {
          newGym: V('绳索三头下压（100%原重）', '新馆 · 龙门架', 25, 2, [15, 12], { seat: '插销档位' }),
          oldGym: V('绳索三头下压（100%原重）', '旧馆 · 龙门架', 25, 2, [15, 12], { seat: '插销档位' }),
          home: V('哑铃臂屈伸（100%原重）', '家庭 · 哑铃（单只计）', 10, 2, [15, 12], { seat: '肘尖朝上' }),
        },
        prescription: P(2, 12, 15, 1, 60),
        tempoGuide: TEMPO_ISO,
        media: M('triceps', ['原重巩固', '2组']),
      },
    ],
    prescription: P(2, 12, 15, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('biceps', ['超级组', 'A+B连做']),
  },

  // ============================== LINDA（全程死手护腕模式） ==============================
  // ---------- Day 1 臀腿重装日 ----------
  {
    id: 'linda_d1_e1',
    user: 'linda',
    day: 1,
    order: 'A1 快速蹬伸',
    muscleGroup: 'quads',
    category: 'power',
    venues: ALL,
    variants: {
      newGym: V('坐姿腿举快速蹬伸', '爆发力激活 · 50%正式重', 25, 3, [5, 5, 5], { seat: '踏板居中' }),
      oldGym: V('倒蹬快速蹬伸', '旧馆 · 爆发力激活', 30, 3, [5, 5, 5], { seat: '踏板居中' }),
      home: V('哑铃快速分腿蹲', '家庭 · 爆发力替代', 5, 3, [5, 5, 5], { seat: '徒手或持铃' }),
    },
    prescription: P(3, 5, 5, 3, 120),
    tempoGuide: TEMPO_POWER,
    media: M('power_leg', ['爆发加速', '末端15°刹车']),
  },
  {
    id: 'linda_d1_e2a',
    user: 'linda',
    day: 1,
    order: '主项1A 臀推',
    muscleGroup: 'glutes_hams',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图7】INSIGHT 挂片臀推机', '图7 · 挂片臀推', 30, 4, [15, 12, 12, 10], { plate: true, seat: '肩胛靠凳沿' }),
      oldGym: V('史密斯机臀推', '旧馆 · 史密斯', 30, 4, [15, 12, 12, 10], { seat: '肩胛靠凳沿' }),
      home: V('背靠凳哑铃臀推', '家庭 · 哑铃', 15, 4, [15, 12, 12, 10], { seat: '肩胛靠凳沿' }),
    },
    prescription: P(4, 10, 15, 2, 150),
    tempoGuide: TEMPO_COMPOUND,
    media: M('hip_thrust', ['顶峰夹紧停1秒', '下巴微收']),
  },
  {
    id: 'linda_d1_e2b',
    user: 'linda',
    day: 1,
    order: '主项1B 单腿臀推（已并入臀推递减组）',
    muscleGroup: 'glutes_hams',
    category: 'compound',
    // V2.9.1 修正：深层单腿臀推紧随大重量双腿臀推，臀大肌力竭后腰椎易产生过度剪切力，
    // 故精简并入臀推机递减组。保留数据以兼容历史打卡记录，但不再进入任何场馆牌堆。
    venues: [],
    variants: {
      newGym: V('单腿 / B-Stance 偏重臀推', '新馆 · 臀推机', 15, 2, [15, 12], { seat: '单腿支撑' }),
      oldGym: V('单腿 / B-Stance 偏重臀推', '旧馆 · 史密斯', 15, 2, [15, 12], { seat: '单腿支撑' }),
      home: V('单腿臀推', '家庭 · 自重/哑铃', 10, 2, [15, 12], { seat: '单腿支撑' }),
    },
    prescription: P(2, 12, 15, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('hip_thrust', ['单腿偏重', '顶峰停1秒']),
  },
  {
    id: 'linda_d1_e3a',
    user: 'linda',
    day: 1,
    order: '主项2A 坐姿腿弯举',
    muscleGroup: 'glutes_hams',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('坐姿腿弯举机', '新馆 · 插销器械', 20, 3, [15, 15, 12], { seat: '滚轴压踝上' }),
      oldGym: V('坐姿腿弯举', '旧馆 · 插销器械', 20, 3, [15, 15, 12], { seat: '滚轴压踝上' }),
      home: V('仰卧滑盘腿弯举', '家庭 · 滑盘', 0, 3, [15, 15, 12], { seat: '仰卧脚跟置滑盘' }),
    },
    prescription: P(3, 12, 15, 1, 90),
    tempoGuide: TEMPO_ISO,
    media: M('leg_curl', ['顶峰停1秒', '离心2秒']),
  },
  {
    id: 'linda_d1_e3b',
    user: 'linda',
    day: 1,
    order: '主项2B 俯卧腿弯举',
    muscleGroup: 'glutes_hams',
    category: 'isolation',
    venues: COMMERCIAL,
    variants: {
      newGym: V('俯卧腿弯举机', '新馆 · 插销器械', 15, 2, [15, 12], { seat: '俯卧滚轴压踝上' }),
      oldGym: V('俯卧腿弯举机', '旧馆 · 插销器械', 15, 2, [15, 12], { seat: '俯卧滚轴压踝上' }),
    },
    prescription: P(2, 12, 15, 1, 90),
    tempoGuide: TEMPO_ISO,
    media: M('leg_curl', ['顶峰停1秒', '离心2秒']),
  },
  {
    id: 'linda_d1_e4a',
    user: 'linda',
    day: 1,
    order: '主项3A 宽距倒蹬',
    muscleGroup: 'quads',
    category: 'compound',
    venues: COMMERCIAL,
    variants: {
      newGym: V('高脚位宽距坐姿倒蹬机', '新馆 · 插销倒蹬', 45, 4, [15, 15, 12, 12], { seat: '脚踩踏板偏高偏宽' }),
      oldGym: V('45°倒蹬机', '旧馆 · 倒蹬机', 50, 4, [15, 15, 12, 12], { seat: '高脚宽距' }),
    },
    prescription: P(4, 12, 15, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('leg_press', ['高脚位', '宽站距']),
  },
  {
    id: 'linda_d1_e4b',
    user: 'linda',
    day: 1,
    order: '主项3B 保加利亚分腿蹲',
    muscleGroup: 'quads',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('死手金属钩保加利亚分腿蹲', '新馆 · 哑铃（单只计）', 7.5, 3, [12, 12, 10], { seat: '后脚搭凳面' }),
      oldGym: V('死手金属钩保加利亚分腿蹲', '旧馆 · 哑铃（单只计）', 7.5, 3, [12, 12, 10], { seat: '后脚搭凳面' }),
      home: V('死手金属钩保加利亚分腿蹲', '家庭 · 哑铃（单只计）', 7.5, 3, [12, 12, 10], { seat: '后脚搭凳面' }),
    },
    prescription: P(3, 10, 12, 2, 90),
    tempoGuide: TEMPO_COMPOUND,
    media: M('lunge', ['后脚搭凳', '躯干前倾15°']),
  },
  {
    id: 'linda_d1_e5a',
    user: 'linda',
    day: 1,
    order: '主项4A 奥杆RDL',
    muscleGroup: 'glutes_hams',
    category: 'compound',
    venues: COMMERCIAL,
    variants: {
      newGym: V('【图1】金属钩奥杆杠铃 RDL', '图1 · 金属钩护腕', 25, 3, [12, 12, 10], { plate: true, seat: '金属钩零抓握' }),
      oldGym: V('金属钩杠铃 RDL', '旧馆 · 金属钩护腕', 25, 3, [12, 12, 10], { seat: '金属钩零抓握' }),
    },
    prescription: P(3, 10, 12, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('hinge', ['臀向后推', '底端停1秒']),
  },
  {
    id: 'linda_d1_e5b',
    user: 'linda',
    day: 1,
    order: '主项4B 哑铃RDL',
    muscleGroup: 'glutes_hams',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('金属钩双手哑铃 RDL（单只计）', '新馆 · 哑铃', 10, 3, [15, 12, 12], { seat: '金属钩零抓握' }),
      oldGym: V('金属钩双手哑铃 RDL（单只计）', '旧馆 · 哑铃', 10, 3, [15, 12, 12], { seat: '金属钩零抓握' }),
      home: V('金属钩双手哑铃 RDL（单只计）', '家庭 · 哑铃', 10, 3, [15, 12, 12], { seat: '金属钩零抓握' }),
    },
    prescription: P(3, 12, 15, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('hinge', ['臀向后推', '底端停1秒']),
  },
  {
    id: 'linda_d1_e6',
    user: 'linda',
    day: 1,
    order: '收尾 核心',
    muscleGroup: 'arms',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('核心平板支撑 Plank', '新馆 · 徒手（按秒）', 0, 3, [45, 45, 45], { seat: '收紧腹背' }),
      oldGym: V('核心平板支撑 Plank', '旧馆 · 徒手（按秒）', 0, 3, [45, 45, 45], { seat: '收紧腹背' }),
      home: V('核心平板支撑 Plank', '家庭 · 徒手（按秒）', 0, 3, [45, 45, 45], { seat: '收紧腹背' }),
    },
    prescription: P(3, 30, 45, 1, 60),
    tempoGuide: TEMPO_CORE,
    media: M('core', ['收紧腹背', '不塌腰']),
  },

  // ---------- Day 3 胸肩雕刻 ----------
  {
    id: 'linda_d3_e1',
    user: 'linda',
    day: 3,
    order: '热身 肩袖',
    muscleGroup: 'shoulders',
    category: 'warmup',
    venues: ALL,
    variants: {
      newGym: V('绳索肩袖外旋热身', '新馆 · 龙门架', 2.5, 2, [15, 15], { seat: '肘贴身' }),
      oldGym: V('弹力带肩袖外旋热身', '旧馆 · 弹力带', 2.5, 2, [15, 15], { seat: '肘贴身' }),
      home: V('弹力带肩袖外旋热身', '家庭 · 弹力带', 0, 2, [15, 15], { seat: '肘贴身' }),
    },
    prescription: P(2, 15, 15, 1, 45),
    tempoGuide: TEMPO_ISO,
    media: M('rotator', ['肘贴身', '慢速控制']),
  },
  {
    id: 'linda_d3_e3a',
    user: 'linda',
    day: 3,
    order: '主项1A 直角肩先锋·免绑扣侧平举',
    muscleGroup: 'shoulders',
    category: 'isolation',
    venues: ['newGym'],
    variants: {
      newGym: V('【图4/5】飞鸟机免绑扣小臂侧平举', '图4/5 · 免绑扣', 10, 4, [18, 15, 15, 15], { seat: '小臂贴垫' }),
    },
    prescription: P(4, 15, 20, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('lateral_raise', ['抬至肩高', '顶峰停0.5秒']),
  },
  {
    id: 'linda_d3_e2a',
    user: 'linda',
    day: 3,
    order: '主项2A 掌根推胸',
    muscleGroup: 'chest',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图6】挂片坐姿推胸机（掌根推）', '图6 · 掌根推', 15, 3, [15, 12, 12], { plate: true, seat: '掌根发力护腕' }),
      oldGym: V('插销坐姿推胸机', '旧馆 · 插销器械', 20, 3, [15, 12, 12], { seat: '掌根发力' }),
      home: V('掌根空握哑铃卧推（单只计）', '家庭 · 哑铃', 7.5, 3, [15, 12, 12], { seat: '掌根空握' }),
    },
    prescription: P(3, 12, 15, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('chest_press', ['掌根发力', '沉肩']),
  },
  {
    id: 'linda_d3_e2b',
    user: 'linda',
    day: 3,
    order: '主项2B 下斜夹胸',
    muscleGroup: 'chest',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('【图4/5】站立飞鸟机下斜夹胸', '图4/5 · 飞鸟机', 10, 3, [15, 15, 12], { seat: '肘微屈' }),
      oldGym: V('蝴蝶机夹胸', '旧馆 · 蝴蝶机', 15, 3, [15, 15, 12], { seat: '背板贴紧' }),
      home: V('弹力带夹胸', '家庭 · 弹力带', 10, 3, [15, 15, 12], { seat: '弹力带固定' }),
    },
    prescription: P(3, 15, 18, 1, 90),
    tempoGuide: TEMPO_ISO,
    media: M('fly', ['顶峰挤压1秒', '离心2秒']),
  },
  {
    id: 'linda_d3_e3b',
    user: 'linda',
    day: 3,
    order: '主项3 脚踝扣侧平举补量',
    muscleGroup: 'shoulders',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('龙门架脚踝扣侧平举', '新馆 · 脚踝扣', 5, 4, [20, 18, 15, 15], { seat: '脚踝扣固定' }),
      oldGym: V('龙门架脚踝扣侧平举', '旧馆 · 脚踝扣', 5, 4, [20, 18, 15, 15], { seat: '脚踝扣固定' }),
      home: V('弹力带小臂侧平举', '家庭 · 弹力带', 5, 4, [20, 18, 15, 15], { seat: '弹力带固定' }),
    },
    prescription: P(4, 15, 20, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('lateral_raise', ['抬至肩高', '顶峰停0.5秒']),
  },
  {
    id: 'linda_d3_e4',
    user: 'linda',
    day: 3,
    order: '主项4 掌根三头下压',
    muscleGroup: 'arms',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('龙门架 V 把掌根三头下压', '新馆 · 掌根推', 12.5, 3, [18, 15, 15], { seat: '纯用掌根' }),
      oldGym: V('龙门架 V 把掌根三头下压', '旧馆 · 掌根推', 12.5, 3, [18, 15, 15], { seat: '纯用掌根' }),
      home: V('弹力带掌根下压', '家庭 · 弹力带', 10, 3, [18, 15, 15], { seat: '纯用掌根' }),
    },
    prescription: P(3, 15, 20, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('triceps', ['伸肘到底停1秒', '掌根发力']),
  },

  // ---------- Day 4 美背直角肩 ----------
  {
    id: 'linda_d4_e1',
    user: 'linda',
    day: 4,
    order: '主项1 宽钩高位下拉',
    muscleGroup: 'back',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('金属宽钩高位下拉', '新馆 · 宽钩护腕', 25, 4, [15, 12, 12, 12], { seat: '宽钩零抓握' }),
      oldGym: V('金属宽钩高位下拉', '旧馆 · 宽钩护腕', 25, 4, [15, 12, 12, 12], { seat: '宽钩零抓握' }),
      home: V('弹力带高位下拉', '家庭 · 弹力带', 15, 4, [15, 12, 12, 12], { seat: '弹力带固定' }),
    },
    prescription: P(4, 12, 15, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('pulldown', ['沉肩', '拉至锁骨']),
  },
  {
    id: 'linda_d4_e2a',
    user: 'linda',
    day: 4,
    order: '主项2A 胸垫划船',
    muscleGroup: 'back',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图9/11】插销式胸垫划船', '图9/11 · 插销', 20, 3, [15, 12, 12], { seat: '胸垫贴紧' }),
      oldGym: V('插销式胸垫划船', '旧馆 · 插销', 20, 3, [15, 12, 12], { seat: '胸垫贴紧' }),
      home: V('胸部支撑金属钩哑铃划船（单只计）', '家庭 · 哑铃', 7.5, 3, [15, 12, 12], { seat: '趴凳支撑' }),
    },
    prescription: P(3, 12, 15, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('row', ['沉肩用手肘拉', '顶峰夹紧']),
  },
  {
    id: 'linda_d4_e2b',
    user: 'linda',
    day: 4,
    order: '主项2B 长臂划船',
    muscleGroup: 'back',
    category: 'compound',
    venues: COMMERCIAL,
    variants: {
      newGym: V('【图10/12】挂片式长臂坐姿划船', '图10/12 · 挂片', 10, 3, [15, 12, 12], { plate: true, seat: '胸垫贴紧' }),
      oldGym: V('坐姿宽钩绳索划船', '旧馆 · 龙门架', 20, 3, [15, 12, 12], { seat: '宽钩零抓握' }),
    },
    prescription: P(3, 12, 15, 2, 120),
    tempoGuide: TEMPO_COMPOUND,
    media: M('row', ['沉肩用手肘拉', '顶峰夹紧']),
  },
  {
    id: 'linda_d4_e3a',
    user: 'linda',
    day: 4,
    order: '主项3A 后束飞鸟',
    muscleGroup: 'shoulders',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('【图4/5】站立后束飞鸟机', '图4/5 · REAR', 10, 3, [18, 15, 15], { seat: '胸垫贴紧' }),
      oldGym: V('蝴蝶机反向后束', '旧馆 · 蝴蝶机', 15, 3, [18, 15, 15], { seat: '反坐胸贴靠背' }),
      home: V('俯身后束飞鸟（单只计）', '家庭 · 哑铃', 5, 3, [18, 15, 15], { seat: '俯身约30°' }),
    },
    prescription: P(3, 15, 20, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('rear_delt', ['向后展肩停1秒', '缓慢还原']),
  },
  {
    id: 'linda_d4_e3b',
    user: 'linda',
    day: 4,
    order: '主项3B 脚踝扣面拉',
    muscleGroup: 'shoulders',
    category: 'isolation',
    venues: COMMERCIAL,
    variants: {
      newGym: V('龙门架脚踝扣面拉 Face Pull', '新馆 · 脚踝扣', 12.5, 3, [18, 15, 15], { seat: '滑轮至面部高' }),
      oldGym: V('龙门架脚踝扣面拉 Face Pull', '旧馆 · 脚踝扣', 12.5, 3, [18, 15, 15], { seat: '滑轮至面部高' }),
    },
    prescription: P(3, 15, 20, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('rear_delt', ['向后展肩停1秒', '缓慢还原']),
  },
  {
    id: 'linda_d4_e4',
    user: 'linda',
    day: 4,
    order: '主项4 侧平举补量',
    muscleGroup: 'shoulders',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('【图4/5】免绑扣侧平举（直角肩补量）', '图4/5 · 免绑扣', 10, 3, [18, 15, 15], { seat: '小臂贴垫' }),
      oldGym: V('脚踝扣侧平举（补量）', '旧馆 · 脚踝扣', 5, 3, [18, 15, 15], { seat: '脚踝扣固定' }),
      home: V('弹力带侧平举（补量）', '家庭 · 弹力带', 5, 3, [18, 15, 15], { seat: '弹力带固定' }),
    },
    prescription: P(3, 15, 20, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('lateral_raise', ['抬至肩高', '顶峰停0.5秒']),
  },
  {
    id: 'linda_d4_e5',
    user: 'linda',
    day: 4,
    order: '主项5 二头弯举',
    muscleGroup: 'arms',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('龙门架脚踝扣小臂二头弯举', '新馆 · 脚踝扣', 7.5, 3, [15, 15, 12], { seat: '脚踝扣固定' }),
      oldGym: V('龙门架脚踝扣小臂二头弯举', '旧馆 · 脚踝扣', 7.5, 3, [15, 15, 12], { seat: '脚踝扣固定' }),
      home: V('牧师凳虚握弯举（单只计）', '家庭 · 哑铃', 5, 3, [15, 15, 12], { seat: '虚握护腕' }),
    },
    prescription: P(3, 12, 15, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('biceps', ['弯起顶峰停1秒', '底部留10°微屈']),
  },

  // ---------- Day 5 第二遍扩次日（85%） ----------
  {
    id: 'linda_d5_e1',
    user: 'linda',
    day: 5,
    order: '1 臀推85%',
    muscleGroup: 'glutes_hams',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图7】臀推机（85%扩次）', '主日 85%', 25, 3, [15, 15, 12], { plate: true, seat: '同 Day1 主项1A' }),
      oldGym: V('史密斯臀推（85%扩次）', '旧馆 85%', 25, 3, [15, 15, 12], { seat: '同主日' }),
      home: V('哑铃臀推（85%扩次）', '家庭 85%', 12.5, 3, [15, 15, 12], { seat: '同主日' }),
    },
    prescription: P(3, 12, 16, 2, 120, ['linda_d1_e2a', 'linda_d1_e2b']),
    tempoGuide: TEMPO_COMPOUND,
    media: M('hip_thrust', ['85%重量', '冲12-16次']),
  },
  {
    id: 'linda_d5_e2',
    user: 'linda',
    day: 5,
    order: '2 坐姿腿弯举85%',
    muscleGroup: 'glutes_hams',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('坐姿腿弯举机（85%扩次）', '主日 85%', 17.5, 3, [15, 15, 15], { seat: '同 Day1 主项2A' }),
      oldGym: V('坐姿腿弯举（85%扩次）', '旧馆 85%', 17.5, 3, [15, 15, 15], { seat: '同主日' }),
      home: V('仰卧滑盘腿弯举（85%扩次）', '家庭 85%', 0, 3, [15, 15, 15], { seat: '同主日' }),
    },
    prescription: P(3, 12, 18, 2, 90, ['linda_d1_e3a', 'linda_d1_e3b']),
    tempoGuide: TEMPO_ISO,
    media: M('leg_curl', ['85%重量', '冲12-18次']),
  },
  {
    id: 'linda_d5_e3a',
    user: 'linda',
    day: 5,
    order: '3A 推胸/卧推85%',
    muscleGroup: 'chest',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图6】坐姿推胸（85%扩次）', '图6 · 85%', 12.5, 3, [15, 15, 12], { plate: true, seat: '掌根发力' }),
      oldGym: V('插销坐姿推胸（85%扩次）', '旧馆 85%', 17.5, 3, [15, 15, 12], { seat: '掌根发力' }),
      home: V('掌根哑铃卧推（85%，单只计）', '家庭 85%', 6, 3, [15, 15, 12], { seat: '掌根空握' }),
    },
    prescription: P(3, 12, 16, 2, 120, ['linda_d3_e2a', 'linda_d3_e2b']),
    tempoGuide: TEMPO_COMPOUND,
    media: M('chest_press', ['85%重量', '冲12-16次']),
  },
  {
    id: 'linda_d5_e3b',
    user: 'linda',
    day: 5,
    order: '3B 飞鸟夹胸85%',
    muscleGroup: 'chest',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('【图4/5】飞鸟机夹胸（85%扩次）', '图4/5 · 85%', 8, 3, [15, 15, 15], { seat: '同 Day3' }),
      oldGym: V('蝴蝶机夹胸（85%扩次）', '旧馆 85%', 12.5, 3, [15, 15, 15], { seat: '同主日' }),
      home: V('弹力带夹胸（85%扩次）', '家庭 85%', 8, 3, [15, 15, 15], { seat: '同主日' }),
    },
    prescription: P(3, 15, 18, 1, 90, ['linda_d3_e3a', 'linda_d3_e3b']),
    tempoGuide: TEMPO_ISO,
    media: M('fly', ['85%重量', '冲15-18次']),
  },
  {
    id: 'linda_d5_e4a',
    user: 'linda',
    day: 5,
    order: '4A 胸垫划船85%',
    muscleGroup: 'back',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('【图9/11】插销式胸垫划船（85%）', '图9/11 · 85%', 17.5, 3, [15, 15, 12], { seat: '胸垫贴紧' }),
      oldGym: V('插销式胸垫划船（85%扩次）', '旧馆 85%', 17.5, 3, [15, 15, 12], { seat: '同主日' }),
      home: V('金属钩哑铃划船（85%，单只计）', '家庭 85%', 6, 3, [15, 15, 12], { seat: '同主日' }),
    },
    prescription: P(3, 12, 16, 2, 120, ['linda_d4_e2a', 'linda_d4_e2b']),
    tempoGuide: TEMPO_COMPOUND,
    media: M('row', ['85%重量', '冲12-16次']),
  },
  {
    id: 'linda_d5_e4b',
    user: 'linda',
    day: 5,
    order: '4B 宽钩下拉85%',
    muscleGroup: 'back',
    category: 'compound',
    venues: ALL,
    variants: {
      newGym: V('金属宽钩高位下拉（85%扩次）', '新馆 · 85%', 20, 3, [15, 15, 12], { seat: '宽钩零抓握' }),
      oldGym: V('金属宽钩高位下拉（85%扩次）', '旧馆 · 85%', 20, 3, [15, 15, 12], { seat: '宽钩零抓握' }),
      home: V('弹力带高位下拉（85%扩次）', '家庭 85%', 12.5, 3, [15, 15, 12], { seat: '同主日' }),
    },
    prescription: P(3, 12, 16, 2, 120, ['linda_d4_e1', 'linda_d4_e2b']),
    tempoGuide: TEMPO_COMPOUND,
    media: M('pulldown', ['85%重量', '冲12-16次']),
  },
  {
    id: 'linda_d5_e5',
    user: 'linda',
    day: 5,
    order: '5 侧平举原重',
    muscleGroup: 'shoulders',
    category: 'isolation',
    venues: ALL,
    variants: {
      newGym: V('免绑扣侧平举（100%原重）', '图4/5 · 原重巩固', 10, 3, [18, 15, 15], { seat: '同 Day3' }),
      oldGym: V('脚踝扣侧平举（100%原重）', '旧馆 · 原重巩固', 5, 3, [18, 15, 15], { seat: '同主日' }),
      home: V('弹力带侧平举（100%原重）', '家庭 · 原重巩固', 5, 3, [18, 15, 15], { seat: '同主日' }),
    },
    prescription: P(3, 15, 20, 1, 60, 'linda_d3_e3a'),
    tempoGuide: TEMPO_ISO,
    media: M('lateral_raise', ['100%原重量']),
  },
  {
    id: 'linda_d5_ss1',
    user: 'linda',
    day: 5,
    order: '6 同机位超级组（面拉+三头下压）',
    muscleGroup: 'shoulders',
    category: 'isolation',
    venues: ALL,
    type: 'superset',
    subExercises: [
      {
        id: 'linda_d5_ss1_a',
        user: 'linda',
        day: 5,
        order: '超级组A 高位面拉/后束飞鸟',
        muscleGroup: 'shoulders',
        category: 'isolation',
        venues: ALL,
        variants: {
          // V2.9.1：新馆改为「单绳索高位面拉」，与 B 段三头下压共用同一龙门架滑轮，
          // 下调插销 3 秒完成切换，消除高峰期独占两个龙门架的器械占位冲突
          newGym: V('【龙门架】单绳索高位面拉（同机位）', '龙门架 · 高位面拉', 10, 2, [18, 15], { seat: '绳索取高位' }),
          oldGym: V('蝴蝶机反向后束（原重）', '旧馆 · 原重', 15, 2, [18, 15], { seat: '反坐' }),
          home: V('俯身后束飞鸟（原重，单只计）', '家庭 · 原重', 5, 2, [18, 15], { seat: '俯身30°' }),
        },
        prescription: P(2, 15, 20, 1, 60),
        tempoGuide: TEMPO_ISO,
        media: M('rear_delt', ['原重巩固', '2组']),
      },
      {
        id: 'linda_d5_ss1_b',
        user: 'linda',
        day: 5,
        order: '超级组B 掌根三头下压',
        muscleGroup: 'arms',
        category: 'isolation',
        venues: ALL,
        variants: {
          newGym: V('掌根三头下压（原重）', '新馆 · 掌根推', 12.5, 2, [18, 15], { seat: '纯用掌根' }),
          oldGym: V('掌根三头下压（原重）', '旧馆 · 掌根推', 12.5, 2, [18, 15], { seat: '纯用掌根' }),
          home: V('弹力带掌根下压（原重）', '家庭 · 掌根', 10, 2, [18, 15], { seat: '纯用掌根' }),
        },
        prescription: P(2, 15, 20, 1, 60),
        tempoGuide: TEMPO_ISO,
        media: M('triceps', ['原重巩固', '2组']),
      },
    ],
    prescription: P(2, 15, 20, 1, 60),
    tempoGuide: TEMPO_ISO,
    media: M('rear_delt', ['超级组', 'A+B连做']),
  },
]

/** V2.5：统计与历史检索所需的全量动作清单（供 AnalyticsModal 使用） */
export const ALL_EXERCISES = PLAN_LIBRARY

/** 每天的元信息（Day 2 / 6 为有氧，7 / 8 为静息） */
export const DAY_META = [
  { day: 1, type: 'strength', title: '下肢重装日', sub: '爆发力 + 股四头 + 伸髋后链', emoji: '🟢' },
  { day: 2, type: 'zone2', title: '洗刷日', sub: 'Zone 2 主动恢复跑', emoji: '🔵' },
  { day: 3, type: 'strength', title: '铠甲日', sub: '推力：推胸 + 站立飞鸟 + 三头', emoji: '🟠' },
  { day: 4, type: 'strength', title: '插件日', sub: '拉力：划船 + 后束 + 二头', emoji: '🟣' },
  { day: 5, type: 'strength', title: '第二遍扩次日', sub: '85% 重量努力冲次数', emoji: '🟡' },
  { day: 6, type: 'hiit', title: '绞肉机日', sub: '4×4 HIIT 间歇', emoji: '🔴' },
  { day: 7, type: 'rest', title: '静息日', sub: '严禁摸铁，超量恢复', emoji: '⚪' },
  { day: 8, type: 'rest', title: '静息日', sub: '中枢神经与肌糖原恢复', emoji: '⚪' },
]

export const USERS = {
  leo: { key: 'leo', label: 'Leo', emoji: '🦁', accent: 'sky', avatar: '/images/leo-avatar.png' },
  linda: { key: 'linda', label: 'Linda', emoji: '🦢', accent: 'rose', avatar: '/images/linda-avatar.jpg' },
}

export const VENUE_MODES = {
  newGym: { key: 'newGym', label: '🌟乐刻新馆', hint: 'Leo帮挂片/插销神机' },
  oldGym: { key: 'oldGym', label: '🏢传统旧馆', hint: '经典插销器械 + 龙门架' },
  home: { key: 'home', label: '🏠家庭重装', hint: '37KG哑铃凳 + 弹力带/金属钩' },
}

/**
 * 根据当前用户、日期(Day 1-8) 与 场馆模式(newGym / oldGym / home)
 * 返回该场馆专属的动作列表，并合并场馆特有的组数、次数与器械信息。
 */
export function getExercisesForDayAndVenue(user, day, venueMode) {
  return PLAN_LIBRARY.filter(
    (item) => item.user === user && item.day === Number(day) && item.venues.includes(venueMode)
  ).map((item) => {
    const v = item.variants?.[venueMode] || item.variants?.newGym || {}
    return {
      ...item,
      activeVariant: {
        name: v.name || item.order || item.id,
        machineCode: v.machineCode || '',
        isPlateLoaded: Boolean(v.isPlateLoaded),
        defaultSeatNote: v.defaultSeatNote || '标准机位',
      },
      prescription: {
        ...item.prescription,
        ...(v.prescription || {}),
        repRange: v.repRange || item.prescription?.repRange || [10, 12],
        sets: v.sets ?? item.prescription?.sets ?? 3,
      },
    }
  })
}

/**
 * V2.6 合并 AI 导入的自定义计划后的当日动作列表
 * - customPlan 为空 → 等价于 getExercisesForDayAndVenue（内置 ACSM 2026 计划）
 * - customPlan 中命中 user + day + venueMode 的条目按 id 覆盖或追加
 */
export function buildDayExercises(user, day, venueMode, customPlan) {
  const base = getExercisesForDayAndVenue(user, day, venueMode)
  if (!Array.isArray(customPlan) || !customPlan.length) return base

  const customForDay = customPlan.filter(
    (it) =>
      it.user === user &&
      Number(it.day) === Number(day) &&
      (!it.venues || it.venues.includes(venueMode))
  )
  if (!customForDay.length) return base

  const merged = new Map(base.map((x) => [x.id, x]))
  for (const item of customForDay) {
    const v = item.variants?.[venueMode] || item.variants?.newGym || {}
    merged.set(item.id, {
      ...item,
      activeVariant: {
        name: v.name || item.order || item.id,
        machineCode: v.machineCode || '',
        isPlateLoaded: Boolean(v.isPlateLoaded),
        defaultSeatNote: v.defaultSeatNote || '标准机位',
      },
      prescription: {
        ...(item.prescription || {}),
        ...(v.prescription || {}),
        repRange: v.repRange || item.prescription?.repRange || [8, 12],
        sets: v.sets ?? item.prescription?.sets ?? 3,
      },
      tempoGuide: item.tempoGuide || TEMPO_COMPOUND,
      media: item.media || { keyPointsOverlay: [] },
    })
  }
  return [...merged.values()]
}

/**
 * V2.8 扁平化：将超级组展开为子动作 A / B 两个独立条目
 * 供「每日清算卡」与「ACSM 周容量统计」使用，避免顶层无 variants 导致报错或漏算
 */
// V2.9：超级组展开逻辑已独立为 utils/deckFlattener.js（清算卡与 ACSM 周容量审计共用）
// 此处保留同名导出，保证既有引用向后兼容
export { flattenDayExercises } from './deck.js'
